### ISSUE TITLE
Missing "keyboard" external dependency

### ISSUE THREAD

**Issue by LucasAlfare** [Samuel-de-Oliveira/CanUseTimer#2]
The program seems can not work since doesn't exists in the project any reference to a package called ```keyboard```. This package was referred in a ```import``` statement [here](https://github.com/Samuel-de-Oliveira/CanUseTimer/blob/main/lib/__init__.py#L2).

The bug aparently can be solved by **manually** installing the package, via ```pip```/```pip3``` tool, however is highly important to manage properly all dependecies before a release in order to make application run in other machines without those packages previously installed.

As hint, try to find a way to build the application with all dependencies packed inside project folder or even create a script to download all of then to the **project local** folder. :)

**Comment by LucasAlfare** [comment]
For reference, check this solution out:

[Stackoverflow link](https://stackoverflow.com/a/68796841/4563960)

**Comment by Samuel-de-Oliveira** [comment]
Hello, when I start the project I aways think in create the software to be "battery included", because this I had created installer (You probably don't saw), you can see about it in the wiki.

About this I have edited README.md, now have a table of downloads of unstable and stable versions, sorry per not specify this.

But actualy is a good idea place a requeriments.txt in directory, thanks anyway.

**Comment by LucasAlfare** [comment]
Great, thats should be fine to manage dependencies for now via ```pip``` tool instead manually by a ```shell``` script.

Also, I recommed put those dependencies in same application directory, instead installing then "globally" in the users machines. As are few dependencies is ok put then in same app folder, making easy unstalling, as well.

For reference, check [this answer](https://stackoverflow.com/a/53925671) in Stackoverflow.
